### ISSUE TITLE
JavaScript error on start

### ISSUE THREAD

**Issue by PaulKeefe** [BZCoding/SkelEktron#2]
Running npm start on macOS, I get this error:

App threw an error during load
Error: Cannot find module 'electron-is-dev'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/me/Projects/SkelEktron/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/me/Projects/SkelEktron/app/lib/log.js:14:15)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

Is there a missing dependency, or something else that I need to install?

**Comment by casanueva** [comment]
Happened to me to. Have you solved this?

btw, running on windows and it just happens when i try to run the exe that i build. I solved the start problem by installing electron-is-dev

**Comment by casanueva** [comment]
Hey, i resolved this just now. You need to install "electron-is-dev" in both the root and the app folder. Its listed as a dependency in the root, but in the package file in "app" its not listed as a dependency.

**Comment by PaulKeefe** [comment]
I installed it in both places that you suggested and now I get this:
2016-10-03T15:10:36.207Z - <Error> Caught unhandled exception: Error: Cannot find module 'electron-debug'
